/* ==========================================================================
 * 【生成，不许手改】词条正文的两份资产 —— 由 0.1.3 的参考实现产出。
 *
 * 生成：powershell -File tools/make-entry-assets.ps1
 * 来源：0.1.3/src/Dictionary/EntryDocument.cs 的两个 `private const string`
 *       （`BaseStyle` 与 `BridgeScript`，走反射读出来，**一个字节都没改**）
 *
 * ⚠️ 七百多行的 CSS + JS，**绝不许手抄或手改**：抄错一个转义符的症状是
 *    词条页莫名其妙地坏（桥接不生效、样式丢一半），最难查的一类。
 *    要改它们，先改参考实现（但 0.1.3 已冻结），或者在 0.2.0 里另立一份
 *    并说明为什么与参考实现不同。
 * ========================================================================== */

#ifndef DSH_ENTRY_ASSETS_H
#define DSH_ENTRY_ASSETS_H

/*
 * ⚠️ 这两段字符串**超过了 C99 要求编译器至少支持的长度**（4095 字符）。
 *    C99 §5.2.4.1 只保证 4095，而真实编译器（gcc / clang / MSVC）都远不止；
 *    我们的构建开着 `-pedantic -Werror`，所以在这里**就地**把这个警告关掉 ——
 *    只关这一个文件里的这一条，且包在 `__GNUC__` 判断里（不认识这个 pragma 的
 *    编译器连看都不会看到它，不会因为 -Wunknown-pragmas 变成错误）。
 *
 * 为什么不改成字节数组：那样确实没有长度上限，但**没法 diff** ——
 * 这两段是要跟参考实现逐字节对得上的东西，可读性就是可验证性。
 */
#if defined(__GNUC__)
#pragma GCC diagnostic ignored "-Woverlength-strings"
#endif

/** 词条正文的基础样式（参考实现 `EntryDocument.BaseStyle`，3253 字符）*/
static const char DSH_ENTRY_BASE_STYLE[] =
  "\n"
  ":root { color-scheme: light; }\n"
  "*, *::before, *::after { box-sizing: border-box; }\n"
  "html { background: transparent; }\n"
  "/*\n"
  " * 滚动条**永远占好位**（即「短词条也留那条 10px 的槽」）。\n"
  " *\n"
  " * 不这么写会有一个只在**短词条**上现形的怪相：正文不够长时浏览器不画滚动条，\n"
  " * 于是右边只剩上面那 6px（那 6px 是「16 − 10」为了给滚动条让位才这么小的），\n"
  " * 而左边是 16px —— 同一页文字左边空一条、右边贴着边，看着像版式坏了。\n"
  " * `overflow-y: scroll` 让滚动条槽**恒在**，两侧就都是 16px；\n"
  " * 槽本身是透明的（见下面 ::-webkit-scrollbar-track），不滚动时也不会有滚动条画出来。\n"
  " *\n"
  " * 代价如实记：**短词条**的正文宽度会比原来少 10px（长词条本来就滚动，一个像素不变）——\n"
  " * 换来的是左右对称。见 开发记录 §71。\n"
  " */\n"
  "html { overflow-y: scroll; }\n"
  "body {\n"
  "  margin: 0;\n"
  "  padding: 14px 16px 20px;\n"
  "  /* 右侧只留 6px：滚动条自己占 ~10px，6+10 才和左边那 16px 看起来一样宽。\n"
  "     用户 2026-09：「内容框的 scroll bar 距离右边缘太远，滚动条区域占用了很多内容框空间」——\n"
  "     但**这条必须带 !important**：字典自带的 CSS（.mdd / 同目录散放的 style.css）会整条覆盖\n"
  "     body 的 padding（实测某本测试用词典把它压成四条 12px），而「右边给滚动条留多少」是宿主的版式，\n"
  "     不该由词典说了算。改这个数之前先看下面 ::-webkit-scrollbar 的宽度，两者是配套的\n"
  "     （见 开发记录 §68）。 */\n"
  "  padding-right: 6px !important;\n"
  "  background: transparent;\n"
  "  color: #1f2430;\n"
  "  font-family: \"Segoe UI Variable Text\", \"Segoe UI\", \"Microsoft YaHei UI\", \"Microsoft YaHei\", system-ui, -apple-system, sans-serif;\n"
  "  font-size: 14px;\n"
  "  line-height: 1.68;\n"
  "  -webkit-font-smoothing: antialiased;\n"
  "  overflow-wrap: anywhere;\n"
  "  word-break: break-word;\n"
  "}\n"
  "body > *:first-child { margin-top: 0 !important; }\n"
  "body > *:last-child { margin-bottom: 0 !important; }\n"
  "a { color: #2f6df6; text-decoration: none; }\n"
  "a:hover { text-decoration: underline; }\n"
  "img, video, canvas { max-width: 100%; height: auto; }\n"
  "audio { max-width: 100%; }\n"
  "table { border-collapse: collapse; max-width: 100%; }\n"
  "hr { border: 0; border-top: 1px solid rgba(20, 24, 40, .1); margin: 14px 0; }\n"
  "code, kbd, samp { font-family: \"Cascadia Code\", Consolas, \"SFMono-Regular\", monospace; font-size: .92em; }\n"
  ".lookup-notice {\n"
  "  padding: 14px 16px;\n"
  "  border-radius: 12px;\n"
  "  background: #fff6ed;\n"
  "  color: #8a4b12;\n"
  "  font-size: 13.5px;\n"
  "  line-height: 1.7;\n"
  "}\n"
  ".lookup-notice code { padding: 1px 5px; border-radius: 5px; background: rgba(138, 75, 18, .1); }\n"
  ".lookup-suggests {\n"
  "  margin-top: 10px;\n"
  "  padding-top: 10px;\n"
  "  border-top: 1px dashed rgba(138, 75, 18, .28);\n"
  "  display: flex;\n"
  "  flex-wrap: wrap;\n"
  "  gap: 6px;\n"
  "  align-items: center;\n"
  "}\n"
  ".lookup-suggests a {\n"
  "  display: inline-block;\n"
  "  padding: 2px 10px;\n"
  "  border-radius: 999px;\n"
  "  background: rgba(138, 75, 18, .1);\n"
  "  color: #8a4b12;\n"
  "  text-decoration: none;\n"
  "}\n"
  ".lookup-suggests a:hover { background: rgba(138, 75, 18, .2); text-decoration: none; }\n"
  "/*\n"
  " * 「出路」按钮：这个词在当前词典里没查到的时候，宿主会送来一两个能走下去的方向\n"
  " * （在别的词典里查一次 / 让机器翻译一下）。\n"
  " * 视觉上贴着上面那句提示走，所以是一排小胶囊，不是一个「工具栏」。\n"
  " */\n"
  ".lookup-chips {\n"
  "  display: flex;\n"
  "  flex-wrap: wrap;\n"
  "  gap: 8px;\n"
  "  margin-top: 14px;\n"
  "}\n"
  ".lookup-chip {\n"
  "  font: inherit;\n"
  "  font-size: 13px;\n"
  "  padding: 5px 14px;\n"
  "  border-radius: 999px;\n"
  "  border: 1px solid rgba(47, 109, 246, .28);\n"
  "  background: rgba(47, 109, 246, .08);\n"
  "  color: #2f6df6;\n"
  "  cursor: pointer;\n"
  "}\n"
  ".lookup-chip:hover { background: rgba(47, 109, 246, .16); }\n"
  "::-webkit-scrollbar { width: 10px; height: 10px; }\n"
  "::-webkit-scrollbar-track { background: transparent; }\n"
  "::-webkit-scrollbar-thumb {\n"
  "  background: rgba(90, 100, 125, .3);\n"
  "  border: 3px solid transparent;\n"
  "  border-radius: 8px;\n"
  "  background-clip: padding-box;\n"
  "}\n"
  "::-webkit-scrollbar-thumb:hover { background: rgba(90, 100, 125, .5); background-clip: padding-box; }\n"
  ""
;

/** 注入词条正文的桥接脚本（参考实现 `EntryDocument.BridgeScript`，15958 字符）*/
static const char DSH_ENTRY_BRIDGE_SCRIPT[] =
  "\n"
  "(function () {\n"
  "  // 打一个标记：自动化验证可以据此判断桥接脚本到底跑没跑起来\n"
  "  try { document.documentElement.dataset.lookupBridge = '1'; } catch (e) {}\n"
  "\n"
  "  // 资源根地址从 <base> 读取，脚本本身不需要知道 dictId\n"
  "  var RES_BASE = '';\n"
  "  try {\n"
  "    var baseEl = document.querySelector('base');\n"
  "    if (baseEl && baseEl.href) RES_BASE = baseEl.href;\n"
  "  } catch (e) {}\n"
  "\n"
  "  // 本文档对应哪个词条（宿主用 ?word= 给的）：用来判断「链接是不是指回本词条」\n"
  "  var CURRENT_WORD = '';\n"
  "  try {\n"
  "    var matched = /[?&]word=([^&]*)/.exec(location.search || '');\n"
  "    if (matched) CURRENT_WORD = decodeURIComponent(matched[1]);\n"
  "  } catch (e) {}\n"
  "\n"
  "  /*\n"
  "   * 词典 id：藏在 <base> 的 host 里（https://<词典 id>.dictres.invalid/）。\n"
  "   * 宿主页的播放器要用它拼「外壳域上的那份音频地址」——宿主页的 CSP 只放行同源，\n"
  "   * 直接把词条域这个地址丢过去会被拦掉。文档自己播时用下面的 soundUrl（同域，不受影响）。\n"
  "   */\n"
  "  var DICT_ID = '';\n"
  "  try {\n"
  "    var hostMatch = /^https:\\/\\/([^.]+)\\./.exec(RES_BASE);\n"
  "    if (hostMatch) DICT_ID = hostMatch[1];\n"
  "  } catch (e) {}\n"
  "\n"
  "  /*\n"
  "   * 词典自带的音频。词条里两种写法都见过：\n"
  "   *   sound://GB_brelasdeapple.spx   （LDOCE5）\n"
  "   *   snd://apple__gb_1.spx          （牛津高阶第 9 版）\n"
  "   * 两者都是「播放这段话」，统一按同一个键名处理。\n"
  "   */\n"
  "  function soundKeyOf(raw) {\n"
  "    return String(raw || '').replace(/^(?:sound|snd):\\/\\//i, '').replace(/^[\\\\\\/]+/, '');\n"
  "  }\n"
  "  function isSoundRef(raw) {\n"
  "    return /^(?:sound|snd):\\/\\//i.test(String(raw || ''));\n"
  "  }\n"
  "  function soundUrl(raw) {\n"
  "    var key = soundKeyOf(raw);\n"
  "    if (!key) return '';\n"
  "    // 键名要编码：mdd 里带空格、中文、反斜杠的资源都有\n"
  "    return RES_BASE + '__sound__/' + encodeURIComponent(key);\n"
  "  }\n"
  "\n"
  "  /*\n"
  "   * 有些词典不是靠 <a href> 播，而是自己写 JS 建 <audio> 或 new Audio(地址)。\n"
  "   * 这些地址在浏览器里是取不到的（sound:// 不是真协议），所以顺手改写成上面那条路由，\n"
  "   * 让词典自带的播放逻辑也能用 —— 我们把「取字节」这件事接过来，播放仍旧交给它自己。\n"
  "   */\n"
  "  function rewriteSoundSources(root) {\n"
  "    try {\n"
  "      var scope = root || document;\n"
  "      var nodes = scope.querySelectorAll('[src]');\n"
  "      for (var i = 0; i < nodes.length; i++) {\n"
  "        var value = nodes[i].getAttribute('src');\n"
  "        if (isSoundRef(value)) nodes[i].setAttribute('src', soundUrl(value));\n"
  "      }\n"
  "    } catch (e) {}\n"
  "  }\n"
  "  try {\n"
  "    var NativeAudio = window.Audio;\n"
  "    if (typeof NativeAudio === 'function') {\n"
  "      var SoundAudio = function (src) {\n"
  "        var target = isSoundRef(src) ? soundUrl(src) : src;\n"
  "        return new NativeAudio(target);\n"
  "      };\n"
  "      SoundAudio.prototype = NativeAudio.prototype;\n"
  "      window.Audio = SoundAudio;\n"
  "    }\n"
  "  } catch (e) {}\n"
  "  rewriteSoundSources(document);\n"
  "  window.addEventListener('load', function () { rewriteSoundSources(document); });\n"
  "  setTimeout(function () { rewriteSoundSources(document); }, 400);\n"
  "\n"
  "  function post(payload) {\n"
  "    try { parent.postMessage(Object.assign({ source: 'lookup-entry' }, payload), '*'); } catch (e) {}\n"
  "  }\n"
  "\n"
  "  /*\n"
  "   * 正文里选了文字要告诉宿主：宿主据此在选区旁边浮出「朗读 / 复制」那排按钮。\n"
  "   *\n"
  "   * 为什么必须由这边上报：正文在跨源 sandbox iframe 里，宿主**够不着它的 Selection**；\n"
  "   * 选区的位置也只能在这边量（iframe 视口坐标），宿主再加上 iframe 自己的位置，\n"
  "   * 就换算成了宿主页坐标。\n"
  "   *\n"
  "   * 节流 60ms：拖选时 selectionchange 会连着来，不节流则宿主那边每来一条都要重建按钮。\n"
  "   * 滚动也要跟着报一次 —— 选区在视口里的位置变了，浮层得跟着挪，否则会和文字对不上。\n"
  "   */\n"
  "  var selectionTimer = null;\n"
  "  function reportSelection() {\n"
  "    var text = '';\n"
  "    var rect = null;\n"
  "    try {\n"
  "      var selection = window.getSelection ? window.getSelection() : null;\n"
  "      if (selection && selection.rangeCount > 0 && !selection.isCollapsed) {\n"
  "        text = String(selection.toString() || '')\n"
  "          .replace(/[\\s\\u3000]+/g, ' ')\n"
  "          .replace(/^\\s+|\\s+$/g, '');\n"
  "        var box = selection.getRangeAt(0).getBoundingClientRect();\n"
  "        rect = { left: box.left, top: box.top, width: box.width, height: box.height, bottom: box.bottom };\n"
  "      }\n"
  "    } catch (e) { text = ''; rect = null; }\n"
  "\n"
  "    /*\n"
  "     * 选中的文字要**整段报上来** —— 朗读功能就是「选多少念多少」（长文本由宿主切成几段接着念）。\n"
  "     *\n"
  "     * 这里的上限只防「把整页都选上」这种极端情况：20000 字已经远超任何人想听的量\n"
  "     * （约二十分钟的朗读），真被截到时浮层的提示里会写明「只念前 20000 字」。\n"
  "     * 以前这里是 300 字，用户报的「选长一点的文本读不完」就是它。\n"
  "     */\n"
  "    var clipped = text.length > 20000;\n"
  "    if (clipped) text = text.slice(0, 20000);\n"
  "    /*\n"
  "     * scrollY 一起报：浮层上那个「查词」按钮按下去就换词条了，宿主得把\n"
  "     * 「跳走之前这篇正文读到哪儿了」和当前词条一起压进返回栈，\n"
  "     * 点「返回上一词条」退回来时才不用又从词条顶端重看一遍。\n"
  "     *\n"
  "     * 跟 entry:// 链接那条路（下面 post lookup 的 scrollY）是同一件事、同一个来源，\n"
  "     * 都只能在这边现读 —— 宿主够不着跨域 iframe 的 scrollTop。\n"
  "     * 顺带说清楚：这是**第三个**要 scrollY 的地方，所以边上那个\n"
  "     * 只报「在不在顶部」的 scroll-state 布尔量不能顶替它。\n"
  "     */\n"
  "    var payload = {\n"
  "      type: 'selection',\n"
  "      text: text,\n"
  "      clipped: clipped,\n"
  "      empty: text.length === 0,\n"
  "      scrollY: Math.round(scrollOffset())\n"
  "    };\n"
  "    if (rect) payload.rect = rect;\n"
  "    post(payload);\n"
  "  }\n"
  "  function scheduleSelectionReport() {\n"
  "    if (selectionTimer) clearTimeout(selectionTimer);\n"
  "    selectionTimer = setTimeout(function () { selectionTimer = null; reportSelection(); }, 60);\n"
  "  }\n"
  "  document.addEventListener('selectionchange', scheduleSelectionReport);\n"
  "  document.addEventListener('mouseup', scheduleSelectionReport, true);\n"
  "  document.addEventListener('keyup', scheduleSelectionReport, true);\n"
  "  /*\n"
  "   * 「用户又要开始选东西了」：宿主拿它清掉「这段文字刚被用掉」的记账，\n"
  "   * 于是**重新选同一段**也能照常浮出按钮（不然点了「复制」之后再选一次就没反应）。\n"
  "   * 只认左键：右键是要弹菜单的。\n"
  "   */\n"
  "  document.addEventListener('mousedown', function (event) {\n"
  "    if (event.button !== 0) return;\n"
  "    post({ type: 'selection-start' });\n"
  "  }, true);\n"
  "  window.addEventListener('scroll', function () {\n"
  "    // 有选区时才需要跟着挪；没选区的话滚动跟它无关（别白刷消息）\n"
  "    var selection = window.getSelection ? window.getSelection() : null;\n"
  "    if (selection && selection.rangeCount > 0 && !selection.isCollapsed) scheduleSelectionReport();\n"
  "  }, { passive: true });\n"
  "\n"
  "  // 把正文实际高度报给宿主，让展开面板贴合内容而不是留一大片空白。\n"
  "  // 加 6px 迟滞，避免和宿主的高度调整互相触发造成抖动。\n"
  "  var lastHeight = -1;\n"
  "  function reportHeight() {\n"
  "    try {\n"
  "      var h = Math.max(\n"
  "        document.body ? document.body.scrollHeight : 0,\n"
  "        document.documentElement ? document.documentElement.scrollHeight : 0\n"
  "      );\n"
  "      if (Math.abs(h - lastHeight) < 6) return;\n"
  "      lastHeight = h;\n"
  "      post({ type: 'height', value: h });\n"
  "    } catch (e) {}\n"
  "  }\n"
  "  window.addEventListener('load', reportHeight);\n"
  "  window.addEventListener('resize', reportHeight);\n"
  "  if (window.ResizeObserver) {\n"
  "    try { new ResizeObserver(reportHeight).observe(document.documentElement); } catch (e) {}\n"
  "  }\n"
  "  setTimeout(reportHeight, 50);\n"
  "  setTimeout(reportHeight, 240);\n"
  "\n"
  "  /*\n"
  "   * 正文滚到哪儿了。宿主（悬浮窗）够不着跨域 iframe 的 scrollTop，\n"
  "   * 但「回顶部」按钮的灰/亮得跟着它变，所以由这边上报。\n"
  "   * 只在「是否在顶部」这个状态真的翻转时才发，滚动过程中不会刷屏。\n"
  "   */\n"
  "  var lastAtTop = null;\n"
  "  function scrollOffset() {\n"
  "    return window.scrollY || window.pageYOffset || document.documentElement.scrollTop || 0;\n"
  "  }\n"
  "  function reportScrollState() {\n"
  "    var atTop = scrollOffset() <= 2;\n"
  "    if (atTop === lastAtTop) return;\n"
  "    lastAtTop = atTop;\n"
  "    post({ type: 'scroll-state', atTop: atTop });\n"
  "  }\n"
  "  window.addEventListener('scroll', reportScrollState, { passive: true });\n"
  "  setTimeout(reportScrollState, 60);\n"
  "\n"
  "  /*\n"
  "   * 跳到**本文档内**的锚点。这是词典里的「页面内快速导航」：\n"
  "   * 多词性词条顶部那排 noun / verb，或者搭配框旁边的义项编号，点的都是它。\n"
  "   *\n"
  "   * 目标一般写成 <a name=...>（MDict 词条的老习惯，LDOCE5 就是），\n"
  "   * 也有写成 id 的，所以先按 id 找、再按 name 找。\n"
  "   * 注意：这段脚本在 C# 侧是用「原样字符串」嵌入的，里面不能出现半角双引号，\n"
  "   * 字符串一律用单引号。\n"
  "   */\n"
  "  function scrollToFragment(fragment) {\n"
  "    if (!fragment) return false;\n"
  "    var target = null;\n"
  "    try {\n"
  "      target = document.getElementById(fragment);\n"
  "      if (!target) {\n"
  "        var named = document.getElementsByName(fragment);\n"
  "        if (named && named.length) target = named[0];\n"
  "      }\n"
  "    } catch (e) {}\n"
  "    if (!target) return false;\n"
  "    // 等一帧再滚：词条刚加载完时高度还在变，立刻滚会停在错的位置\n"
  "    var run = function () {\n"
  "      try { target.scrollIntoView({ block: 'start' }); }\n"
  "      catch (e) { try { target.scrollIntoView(); } catch (e2) {} }\n"
  "    };\n"
  "    if (window.requestAnimationFrame) window.requestAnimationFrame(run); else run();\n"
  "    // 地址栏也同步上（除非已经是这个锚点），方便用 :target 之类的样式\n"
  "    try { if (location.hash !== '#' + fragment) location.hash = fragment; } catch (e) {}\n"
  "    return true;\n"
  "  }\n"
  "\n"
  "  /*\n"
  "   * 解析链接目标，返回 { word, fragment }：\n"
  "   *   entry://word          跨词条跳转\n"
  "   *   entry://word#frag     跨词条跳转 + 落在某个义项上\n"
  "   *   entry://#frag         本文档内跳转（LDOCE5 的页面内导航就是这种）\n"
  "   *   #frag                 同上，只是没写 entry://\n"
  "   * 返回 null 表示这个 href 不归这里管。\n"
  "   */\n"
  "  function parseTarget(raw) {\n"
  "    var body;\n"
  "    if (raw.indexOf('entry://') === 0) body = raw.slice('entry://'.length);\n"
  "    else if (raw.charAt(0) === '#') return { word: '', fragment: raw.slice(1) };\n"
  "    else return null;\n"
  "\n"
  "    var hash = body.indexOf('#');\n"
  "    if (hash < 0) return { word: body, fragment: '' };\n"
  "    return { word: body.slice(0, hash), fragment: body.slice(hash + 1) };\n"
  "  }\n"
  "\n"
  "  function isWordChar(ch) {\n"
  "    if (!ch) return false;\n"
  "    var code = ch.charCodeAt(0);\n"
  "    // 撇号（直/弯）与连字符算词内字符，don't / easy-care 才不会被切成两半\n"
  "    if (code === 39 || code === 45 || code === 8217) return true;\n"
  "    return /[0-9A-Za-z\\u00c0-\\u024f\\u4e00-\\u9fff]/.test(ch);\n"
  "  }\n"
  "\n"
  "  /** 鼠标位置下的文字光标（Chromium 两套 API 都试一遍） */\n"
  "  function caretAt(x, y) {\n"
  "    try {\n"
  "      if (document.caretRangeFromPoint) {\n"
  "        var range = document.caretRangeFromPoint(x, y);\n"
  "        if (range) return { node: range.startContainer, offset: range.startOffset };\n"
  "      }\n"
  "      if (document.caretPositionFromPoint) {\n"
  "        var position = document.caretPositionFromPoint(x, y);\n"
  "        if (position) return { node: position.offsetNode, offset: position.offset };\n"
  "      }\n"
  "    } catch (e) {}\n"
  "    return null;\n"
  "  }\n"
  "\n"
  "  /*\n"
  "   * 取鼠标点到的那**一个词**。\n"
  "   *\n"
  "   * 牛津高阶的交叉引用里有这么一类链接：href 写的是整条词组（take care of），\n"
  "   * 而这条词组并不是词库里的词条 —— 它只是别处某个义项里的一段，\n"
  "   * 所以整条词组查不到（「词组里的每个词各自挂着整条词组的 href」看着就像\n"
  "   * 好几个可跳转的词连在一起）。这时按用户的直觉退一步：查他点到的那个词。\n"
  "   */\n"
  "  function wordAtPoint(x, y, element) {\n"
  "    var caret = caretAt(x, y);\n"
  "    if (caret && caret.node && caret.node.nodeType === 3) {\n"
  "      var text = caret.node.nodeValue || '';\n"
  "      var start = caret.offset;\n"
  "      var end = caret.offset;\n"
  "      while (start > 0 && isWordChar(text.charAt(start - 1))) start--;\n"
  "      while (end < text.length && isWordChar(text.charAt(end))) end++;\n"
  "      var hit = text.slice(start, end);\n"
  "      if (hit) return hit;\n"
  "    }\n"
  "    // 拿不到光标位置（例如脚本触发的点击）就退回锚文本的第一个词\n"
  "    var label = (element && element.textContent ? element.textContent : '').replace(/^\\s+|\\s+$/g, '');\n"
  "    var parts = label.split(/[\\s,;<>\\/]+/);\n"
  "    for (var i = 0; i < parts.length; i++) {\n"
  "      if (parts[i]) return parts[i];\n"
  "    }\n"
  "    return '';\n"
  "  }\n"
  "\n"
  "  document.addEventListener('click', function (event) {\n"
  "    var node = event.target;\n"
  "    while (node && node !== document && !(node.tagName === 'A')) node = node.parentNode;\n"
  "    if (!node || node === document || node.tagName !== 'A') return;\n"
  "    var raw = node.getAttribute('href') || '';\n"
  "    if (!raw) return;\n"
  "\n"
  "    var target = parseTarget(raw);\n"
  "    if (target) {\n"
  "      /*\n"
  "       * 一律 preventDefault。文档里有 <base>，`#xxx` 会被解析成\n"
  "       * 「base 地址 + #xxx」（那是另一个文档）—— 交给浏览器默认行为的话，\n"
  "       * 一点页面内导航链接就把整个词条页面导航没了。\n"
  "       */\n"
  "      event.preventDefault();\n"
  "      var word = target.word;\n"
  "      var fragment = target.fragment;\n"
  "      try { word = decodeURIComponent(word); } catch (e) {}\n"
  "      try { fragment = decodeURIComponent(fragment); } catch (e) {}\n"
  "\n"
  "      /*\n"
  "       * 两种「不用换词条」的情况，就地滚过去就行：\n"
  "       *   - 链接里没写词（`entry://#noun`，LDOCE5 的页面内导航就是这种）\n"
  "       *   - 写的词就是本文档自己（`entry://point#verb` 出现在 point 词条里）\n"
  "       * 后者要是也交给宿主去查一遍，等于把同一个词条重新加载一次再滚，\n"
  "       * 白闪一下不说，宿主的「自链接不记录返回栈」那条规则还会把它吞掉。\n"
  "       */\n"
  "      if (!word || word === CURRENT_WORD) {\n"
  "        if (fragment) scrollToFragment(fragment);\n"
  "        else { try { window.scrollTo(0, 0); } catch (e) {} }\n"
  "        return;\n"
  "      }\n"
  "      /*\n"
  "       * 词组链接顺手把「鼠标点到的那个词」也带上：整条词组查不到时，\n"
  "       * 宿主会拿它再查一次（见 wordAtPoint 的说明）。\n"
  "       *\n"
  "       * scrollY 是「跳走之前这篇正文读到哪儿了」：宿主把它和当前词条一起压进返回栈，\n"
  "       * 点「返回」退回来时再还原到这个位置（而不是又回到词条顶端）。\n"
  "       * 必须在这里现读 —— 宿主够不着跨域 iframe 的 scrollTop，\n"
  "       * 而边上的 scroll 上报只报「在不在顶部」这一个布尔量。\n"
  "       */\n"
  "      var fallbackWord = word.indexOf(' ') >= 0 ? wordAtPoint(event.clientX, event.clientY, node) : '';\n"
  "      post({\n"
  "        type: 'lookup',\n"
  "        word: word,\n"
  "        fragment: fragment,\n"
  "        fallbackWord: fallbackWord,\n"
  "        scrollY: Math.round(scrollOffset())\n"
  "      });\n"
  "      return;\n"
  "    }\n"
  "    if (isSoundRef(raw)) {\n"
  "      /*\n"
  "       * 词典自带的录音（词目发音、例句发音都走这里）。\n"
  "       * 交给宿主播：宿主页里那个复用的 <audio> 才是全局唯一的播放器，\n"
  "       * 同一时刻只该有一个声音在响 —— 点例句喇叭会顶掉正在念的词目发音，这是对的。\n"
  "       */\n"
  "      event.preventDefault();\n"
  "      post({ type: 'play-sound', key: soundKeyOf(raw), dictId: DICT_ID, url: soundUrl(raw) });\n"
  "      return;\n"
  "    }\n"
  "    if (/^https?:/i.test(raw)) {\n"
  "      event.preventDefault();\n"
  "      post({ type: 'open-external-link', url: raw });\n"
  "      return;\n"
  "    }\n"
  "    // 其余未知协议（如 oalecd://）一律拦截，避免 iframe 被导航走\n"
  "    if (!/^javascript:/i.test(raw)) event.preventDefault();\n"
  "  }, true);\n"
  "\n"
  "  // 宿主（悬浮窗）转发过来的指令\n"
  "  window.addEventListener('message', function (event) {\n"
  "    var data = event.data;\n"
  "    if (!data || data.source !== 'lookup-host') return;\n"
  "    if (data.type === 'scroll' && typeof data.delta === 'number') {\n"
  "      try {\n"
  "        window.scrollBy(0, data.delta);\n"
  "      } catch (e) {\n"
  "        try { document.documentElement.scrollTop += data.delta; } catch (e2) {}\n"
  "      }\n"
  "      return;\n"
  "    }\n"
  "    // 跨词条跳转带了锚点：新词条装好之后由宿主喊一声，落回指定的义项\n"
  "    if (data.type === 'scroll-to' && typeof data.fragment === 'string') {\n"
  "      scrollToFragment(data.fragment);\n"
  "      return;\n"
  "    }\n"
  "    /*\n"
  "     * 从别的词条「返回」回来：还原到当初离开这篇正文时读到的那一行，\n"
  "     * 而不是又从词条顶端重新看起（位置是宿主返回栈里存着的，见上面 post lookup 的 scrollY）。\n"
  "     *\n"
  "     * 为什么要分几次落：图片是后加载的，文档装好那一刻还没长到最终高度，\n"
  "     * 一次性滚过去可能被「顶」回去一小截。所以先落一次，过一会儿再补两次 ——\n"
  "     * 但每次补之前先看一眼当前位置是不是还等于我们上次设的值：\n"
  "     * 不等就说明用户已经自己滚走了，那就不再插手（免得跟他抢滚动条）。\n"
  "     */\n"
  "    if (data.type === 'scroll-to-y' && typeof data.y === 'number') {\n"
  "      var wanted = Math.max(0, data.y);\n"
  "      var applied = -1;\n"
  "      var attempts = 0;\n"
  "      var restoreScroll = function () {\n"
  "        attempts++;\n"
  "        if (attempts > 1 && applied >= 0 && Math.abs(scrollOffset() - applied) > 24) return;\n"
  "        try { window.scrollTo(0, wanted); } catch (e) {}\n"
  "        // 回读一次：文档不够高时浏览器会把值夹住，记住夹住之后的真实位置\n"
  "        applied = scrollOffset();\n"
  "        setTimeout(reportScrollState, 30);\n"
  "      };\n"
  "      restoreScroll();\n"
  "      setTimeout(restoreScroll, 180);\n"
  "      setTimeout(restoreScroll, 420);\n"
  "      return;\n"
  "    }\n"
  "    // 宿主点了「回顶部」\n"
  "    if (data.type === 'scroll-top') {\n"
  "      try { window.scrollTo({ top: 0, behavior: 'smooth' }); }\n"
  "      catch (e) { try { window.scrollTo(0, 0); } catch (e2) {} }\n"
  "      // 平滑滚动是异步的，先按「已经在顶部」回报一次，滚动结束后的 scroll 事件会再校准\n"
  "      setTimeout(reportScrollState, 60);\n"
  "      setTimeout(reportScrollState, 400);\n"
  "      return;\n"
  "    }\n"
  "    /*\n"
  "     * 宿主送来「这个词没查到，还能怎么办」的几个出路（见 renderChips）。\n"
  "     *\n"
  "     * 为什么按钮长在**词条正文里**、而不是宿主页里：这一排东西是接着\n"
  "     * 「未在《…》中找到 X」那句提示往下读的，长在同一篇文档里高度才会被一起量进去\n"
  "     * （reportHeight 量的是整个文档），也不会把正文挤掉一截。\n"
  "     * 更要紧的是**滚动位置**：点击时要把「这篇读到哪儿了」一起报给宿主压栈，\n"
  "     * 而宿主够不着跨域 iframe 的 scrollTop —— 文档里的按钮顺手就带上了（和链接点击同一个来源）。\n"
  "     */\n"
  "    if (data.type === 'chips') {\n"
  "      renderChips(data.items);\n"
  "      return;\n"
  "    }\n"
  "  });\n"
  "\n"
  "  /* ------------------------------ 出路按钮 ------------------------------ */\n"
  "\n"
  "  var chips = document.getElementById('lookupChips');\n"
  "  function renderChips(items) {\n"
  "    if (!chips) return;\n"
  "    while (chips.firstChild) chips.removeChild(chips.firstChild);\n"
  "    if (!items || !items.length) {\n"
  "      chips.hidden = true;\n"
  "      reportHeight();\n"
  "      return;\n"
  "    }\n"
  "    for (var i = 0; i < items.length; i++) {\n"
  "      (function (item) {\n"
  "        if (!item || !item.label) return;\n"
  "        var button = document.createElement('button');\n"
  "        button.type = 'button';\n"
  "        button.className = 'lookup-chip';\n"
  "        button.textContent = item.label;\n"
  "        button.setAttribute('data-chip-action', item.action || '');\n"
  "        button.title = item.hint || item.label;\n"
  "        /*\n"
  "         * 用 mousedown 而不是 click：与正文里那些 entry:// 链接同一条规矩 ——\n"
  "         * click 要等 mouseup，中间那一下可能先把选区/焦点弄乱；\n"
  "         * 而这里点下去就是要跳走，早一步决定没有副作用。\n"
  "         */\n"
  "        button.addEventListener('mousedown', function (event) {\n"
  "          event.preventDefault();\n"
  "          post({\n"
  "            type: 'chip',\n"
  "            action: item.action || '',\n"
  "            word: item.word || '',\n"
  "            scrollY: Math.round(scrollOffset())\n"
  "          });\n"
  "        });\n"
  "        chips.appendChild(button);\n"
  "      })(items[i]);\n"
  "    }\n"
  "    chips.hidden = false;\n"
  "    // 按钮多一行，文档就高了一点 —— 重新量一次，别让面板把这一排裁掉\n"
  "    reportHeight();\n"
  "  }\n"
  "})();\n"
  ""
;

#endif /* DSH_ENTRY_ASSETS_H */
